import os

# ==================== FILE PATHS ====================
EXCEL_FILE_PATH = os.getenv("EXCEL_PATH", "Indian_Stocks_Complete_Market_Cap_Classification.xlsx")
REPORTS_FOLDER = os.getenv("REPORTS_FOLDER", "analysis_reports")

# ==================== SERVER SETTINGS ====================
SERVER_HOST = os.getenv("SERVER_HOST", "0.0.0.0")
SERVER_PORT = int(os.getenv("SERVER_PORT", "8080"))
DEBUG_MODE = os.getenv("DEBUG_MODE", "False").lower() == "true"

# ==================== FUNDAMENTAL ANALYSIS THRESHOLDS ====================

# PE Ratio
PE_UNDERVALUED = 15
PE_FAIR_VALUE = 25
PE_EXPENSIVE = 40

# PB Ratio
PB_BELOW_BOOK = 1
PB_REASONABLE = 3
PB_PREMIUM = 5

# ROE (percentage)
ROE_EXCELLENT = 20
ROE_GOOD = 15
ROE_AVERAGE = 10

# Debt to Equity (percentage)
DE_LOW = 50
DE_MODERATE = 100
DE_HIGH = 150

# Dividend Yield (percentage)
DIVIDEND_GOOD = 3
DIVIDEND_MODERATE = 1

# Profit Margin (percentage)
MARGIN_HIGH = 20
MARGIN_DECENT = 10

# Revenue Growth (percentage)
GROWTH_HIGH = 20
GROWTH_GOOD = 10

# ==================== TECHNICAL ANALYSIS THRESHOLDS ====================

# RSI
RSI_OVERSOLD = 30
RSI_APPROACHING_OVERSOLD = 45
RSI_NEUTRAL_HIGH = 55
RSI_APPROACHING_OVERBOUGHT = 70
RSI_OVERBOUGHT = 70

# Stochastic
STOCH_OVERSOLD = 20
STOCH_OVERBOUGHT = 80

# ADX
ADX_TRENDING = 25

# Bollinger Band position
BB_OVERSOLD = 0.2
BB_OVERBOUGHT = 0.8

# Volume ratio
VOLUME_HIGH = 1.5
VOLUME_LOW = 0.5

# ==================== HISTORICAL ANALYSIS THRESHOLDS ====================

# 52-week position (percentage)
POSITION_NEAR_LOW = 30
POSITION_LOWER_HALF = 50
POSITION_UPPER_HALF = 70
POSITION_NEAR_HIGH = 90

# Return thresholds (percentage)
RETURN_STRONG = 30
RETURN_GOOD = 10

# Volatility (annualized, percentage)
VOLATILITY_LOW = 20
VOLATILITY_MODERATE = 35

# Support distance (percentage)
SUPPORT_VERY_CLOSE = 3
SUPPORT_NEAR = 7

# ==================== SCORE ADJUSTMENTS ====================

# Fundamental scores
SCORE_PE_UNDERVALUED = 10
SCORE_PE_FAIR = 5
SCORE_PE_EXPENSIVE = -5
SCORE_PE_OVERVALUED = -10

SCORE_PB_BELOW_BOOK = 10
SCORE_PB_REASONABLE = 5
SCORE_PB_PREMIUM = -5
SCORE_PB_EXPENSIVE = -10

SCORE_ROE_EXCELLENT = 10
SCORE_ROE_GOOD = 5
SCORE_ROE_LOW = -5

SCORE_DE_LOW = 10
SCORE_DE_MODERATE = 5
SCORE_DE_HIGH = -5
SCORE_DE_VERY_HIGH = -10

SCORE_DIVIDEND_GOOD = 5
SCORE_DIVIDEND_MODERATE = 2

SCORE_MARGIN_HIGH = 5
SCORE_MARGIN_DECENT = 2
SCORE_MARGIN_LOSS = -10

SCORE_GROWTH_HIGH = 5
SCORE_GROWTH_GOOD = 2
SCORE_GROWTH_DECLINING = -5

# Technical scores
SCORE_RSI_OVERSOLD = 15
SCORE_RSI_APPROACHING_OVERSOLD = 5
SCORE_RSI_APPROACHING_OVERBOUGHT = -5
SCORE_RSI_OVERBOUGHT = -15

SCORE_MACD_BULLISH = 10
SCORE_MACD_BEARISH = -10

SCORE_MA_BULLISH = 10
SCORE_MA_BEARISH = -10

SCORE_BB_OVERSOLD = 10
SCORE_BB_OVERBOUGHT = -10

SCORE_STOCH_OVERSOLD = 10
SCORE_STOCH_OVERBOUGHT = -10

SCORE_ADX_UPTREND = 5
SCORE_ADX_DOWNTREND = -5

# Historical scores
SCORE_POSITION_NEAR_LOW = 15
SCORE_POSITION_LOWER_HALF = 10
SCORE_POSITION_NEAR_HIGH = -5
SCORE_POSITION_AT_HIGH = -10

SCORE_TREND_BULLISH = 10
SCORE_TREND_BEARISH = -10

SCORE_RETURN_STRONG = 5
SCORE_RETURN_GOOD = 2
SCORE_RETURN_NEGATIVE = -5

SCORE_VOLATILITY_LOW = 5
SCORE_VOLATILITY_HIGH = -5

SCORE_SUPPORT_VERY_CLOSE = 10
SCORE_SUPPORT_NEAR = 5

# ==================== SIGNAL ENGINE SETTINGS ====================

SIGNAL_WEIGHTS = {
    'rsi': 0.15,
    'macd': 0.15,
    'ma_trend': 0.15,
    'bollinger': 0.10,
    'stochastic': 0.10,
    'volume': 0.10,
    'momentum': 0.10,
    'atr_position': 0.05,
    'adx': 0.10,
}

STRONG_SIGNAL_THRESHOLD = 0.15
MODERATE_SIGNAL_THRESHOLD = 0.08
STRONG_SIGNAL_MIN_INDICATORS = 4
MODERATE_SIGNAL_MIN_INDICATORS = 3

# Target/Stop Loss multipliers (ATR based)
TARGET_MULTIPLIER_STRONG = 2.5
TARGET_MULTIPLIER_MODERATE = 2.0
STOP_MULTIPLIER_STRONG = 1.5
STOP_MULTIPLIER_MODERATE = 1.2

# ==================== COMPREHENSIVE ANALYZER SETTINGS ====================

ANALYZER_WEIGHTS = {
    'rsi': 0.12,
    'macd': 0.12,
    'ma_trend': 0.12,
    'bollinger': 0.10,
    'stochastic': 0.10,
    'volume': 0.10,
    'momentum': 0.10,
    'atr_position': 0.08,
    'adx': 0.08,
    'historical': 0.08,
}

BUY_SIGNAL_THRESHOLD = 65
STRONG_BUY_THRESHOLD = 75
SELL_SIGNAL_THRESHOLD = 35
STRONG_SELL_THRESHOLD = 25

FUNDAMENTAL_WEIGHT = 0.30
HISTORICAL_WEIGHT = 0.25
TECHNICAL_WEIGHT = 0.45

# ==================== TRADING PLAN SETTINGS ====================

BEST_ENTRY_TOLERANCE = 0.01
GOOD_ENTRY_TOLERANCE = 0.02
AGGRESSIVE_ENTRY_TOLERANCE = 0.01

TARGET_1_ATR_MULTIPLIER = 2.0
TARGET_2_ATR_MULTIPLIER = 3.5
STOP_LOSS_ATR_MULTIPLIER = 1.5
SUPPORT_STOP_MARGIN = 0.03

# ==================== BACKTESTER SETTINGS ====================

MIN_DATA_DAYS = 50
OUTCOME_1_DAY = 1
OUTCOME_7_DAYS = 5
OUTCOME_30_DAYS = 20

# ==================== DATA FETCHER SETTINGS ====================

DEFAULT_PERIOD = "1y"
DEFAULT_INTERVAL = "1d"
NSE_SUFFIX = ".NS"
BSE_SUFFIX = ".BO"
